import { Inter } from "next/font/google";
import { Provider } from "@/context/store";
import Footers from "@/components/Molecules/foot";
import Nav from "@/components/Molecules/nav";
import "../style/globals.css";
import "../style/swiper.css";
import "bootstrap/dist/css/bootstrap.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "detik health",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Nav></Nav>
          {children}
          <Footers></Footers>
        </Provider>
      </body>
    </html>
  );
}
